# config for loan origination
domain: "lo-domain"
service: "cadence-frontend"
host: "127.0.0.1:7833"
tasklist: "lo-loan_worker-tasklist"
# config for emitting metrics
#prometheus:
#  listenAddress: "127.0.0.1:9098"
